name: Build and Release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CheatDetector
        path: build/libs/*.jar
        
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: CheatDetector
        path: artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 